//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOI4Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\gfx\\army_icons\\")]
        public string PathArmyIcons {
            get {
                return ((string)(this["PathArmyIcons"]));
            }
            set {
                this["PathArmyIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\backup\\")]
        public string PathBackup {
            get {
                return ((string)(this["PathBackup"]));
            }
            set {
                this["PathBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InsigniaGap {
            get {
                return ((int)(this["InsigniaGap"]));
            }
            set {
                this["InsigniaGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int InsigniaWidth {
            get {
                return ((int)(this["InsigniaWidth"]));
            }
            set {
                this["InsigniaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int InsigniaHeight {
            get {
                return ((int)(this["InsigniaHeight"]));
            }
            set {
                this["InsigniaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("army_icons.txt")]
        public string FileArmyIconConfig {
            get {
                return ((string)(this["FileArmyIconConfig"]));
            }
            set {
                this["FileArmyIconConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("army_icons.dds")]
        public string FileArmyIconGraphics {
            get {
                return ((string)(this["FileArmyIconGraphics"]));
            }
            set {
                this["FileArmyIconGraphics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("army_group_icons.dds")]
        public string FileArmyGroupIconGraphics {
            get {
                return ((string)(this["FileArmyGroupIconGraphics"]));
            }
            set {
                this["FileArmyGroupIconGraphics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("navy_icons.dds")]
        public string FileNavyIconGraphics {
            get {
                return ((string)(this["FileNavyIconGraphics"]));
            }
            set {
                this["FileNavyIconGraphics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("army_selected_icons.dds")]
        public string FileArmyIconGraphicsSelected {
            get {
                return ((string)(this["FileArmyIconGraphicsSelected"]));
            }
            set {
                this["FileArmyIconGraphicsSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("army_group_selected_icons.dds")]
        public string FileArmyGroupIconGraphicsSelected {
            get {
                return ((string)(this["FileArmyGroupIconGraphicsSelected"]));
            }
            set {
                this["FileArmyGroupIconGraphicsSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("navy_selected_icons.dds")]
        public string FileNavyIconGraphicsSelected {
            get {
                return ((string)(this["FileNavyIconGraphicsSelected"]));
            }
            set {
                this["FileNavyIconGraphicsSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\interface\\")]
        public string PathInterface {
            get {
                return ((string)(this["PathInterface"]));
            }
            set {
                this["PathInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("theatreselector.gfx")]
        public string FileTheatreSelector {
            get {
                return ((string)(this["FileTheatreSelector"]));
            }
            set {
                this["FileTheatreSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSetupOk {
            get {
                return ((bool)(this["IsSetupOk"]));
            }
            set {
                this["IsSetupOk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBackupOk {
            get {
                return ((bool)(this["IsBackupOk"]));
            }
            set {
                this["IsBackupOk"] = value;
            }
        }
    }
}
